boardgames/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^profileUser/', include('profileUser.urls')),
                       url(r'^tictactoe/', include('tictactoe.urls')),
                       url(r'^$', 'main.views.home', name='boardgames_home'))

# group different patterns
urlpatterns += patterns(
    'django.contrib.auth.views',

    url(r'^login/$', 'login',
        {'template_name': 'login.html'},
        name='boardgames_login'),

    url(r'^logout/$', 'logout',
        {'next_page': 'boardgames_home'},
        name='boardgames_logout')
)

profileUser/urls.py
__author__ = 'jramirez'
from django.conf.urls import patterns, include, url

urlpatterns = patterns('profileUser.views',
                       url(r'^home$', 'home', name='profileUser_home'))

tictactoe/urls.py
__author__ = 'jramirez'
from django.conf.urls import patterns, include, url

urlpatterns = patterns('tictactoe.views',
                       url(r'^invite$', 'new_invitation', name='tictactoe_invite'))

main/models.py
from django.db import models

# Create your models here.

profileUser/models.py
from django.db import models

# Create your models here.

tictactoe/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q


# Create your models here.
GAME_STATUS_CHOICES = (
    ('A', 'ACTIVE'),
    ('F', 'First Player Wins'),
    ('S', 'Second Player Wins'),
    ('D', 'Draw')
)


class GamesManager(models.Manager):
    def games_for_user(self, user):
        return super(GamesManager, self).get_queryset().filter(Q(first_player_id=user.id) | Q(second_player_id=user.id))


class Game(models.Model):
    first_player = models.ForeignKey(User, related_name="games_first_player")
    second_player = models.ForeignKey(User, related_name="games_second_player")
    next_to_move = models.ForeignKey(User, related_name="games_to_move")
    start_time = models.DateTimeField(auto_now_add=True)
    last_active = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, default='A', choices=GAME_STATUS_CHOICES)
    objects = GamesManager()

    def __str__(self):
        return "{0} vs {1}".format(self.first_player, self.second_player)


class Move(models.Model):
    x = models.IntegerField()
    y = models.IntegerField()
    comment = models.CharField(max_length=300)
    game = models.ForeignKey(Game)


class Invitation(models.Model):
    from_user = models.ForeignKey(User, related_name="invitations_sent")
    to_user = models.ForeignKey(User, related_name="invitations_received")
    message = models.CharField(max_length=300)
    timestamp = models.DateTimeField(auto_now_add=True)

tictactoe/forms.py
__author__ = 'jramirez'
from django import forms
from .models import Invitation


class InvitationForm(forms.ModelForm):
    class Meta:
        model = Invitation
        fields = '__all__'

main/views.py
from django.shortcuts import render
from django.http import HttpResponse


def home(request):
    return render(request, "main/home.html", {'message': 'hi there!'})

profileUser/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from tictactoe.models import Game

@login_required()
def home(request):
    my_games = Game.objects.games_for_user(request.user)
    active_games = my_games.filter(status="A")
    finished_games = my_games.exclude(status="A")
    waiting_games = active_games.filter(next_to_move=request.user)
    other_games = active_games.exclude(next_to_move=request.user)
    # dictionary
    context = {'other_games': other_games,
               'waiting_games': waiting_games,
               'finished_games': finished_games}

    return render(request, "profileUser/home.html", context)

tictactoe/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .forms import InvitationForm


@login_required
def new_invitation(request):
    if request.method == 'POST':
        form = InvitationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('profileUser_home')
    else:
        form = InvitationForm()
    return render(request, "tictactoe/new_invitation.html", {'form': form})

main/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Boardgames demo app{% endblock title%}</title>
    {% block styling %}
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.5-dist/css/bootstrap.min.css' %}">
    {% endblock styling %}
</head>
<body>
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
            <li><a href="{% url 'boardgames_logout' %}">Logout</a></li>
        {% else %}
            <li><a href="{% url 'boardgames_login' %}">Login</a></li>
        {% endif %}
    </ul>
    <div class="container">
        {% block content%}
        {% endblock content %}
    </div>
    {% block javascript %}
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script type="text/javascript" src="{% static 'bootstrap-3.3.5-dist/js/bootstrap.min.js' %}"></script>
    {% endblock javascript%}
</body>
</html>

main/templates/login.html
<html>
    <head>
        <title>Please login</title>
    </head>
    <body>
        {% if form.errors %}
        <p class="text-warning">Your username and password didn't match.</p>
        {% endif %}
        <form role="form" class="form-horizontal" method="post" >
            {% csrf_token %}
            {{form}}
            <input class="btn btn-primary" type="submit" value="Login">
            <input type="hidden" name="next" value="{{next}}">
        </form>
    </body>
</html>

main/templates/main/home.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <p>Welcome to the Django fundamentals course. This site was made with <a href="#">Pluralsight</a></p>
        <p><a href="{% url 'boardgames_login' %}">Click here to login</a> or <a href="#">Sign up!</a></p>
    </div>
{% endblock content %}

profileUser/templates/profileUser/home.html
{% extends "base.html" %}

{% block title %}
Overview for {{user.username}}
{% endblock title %}

{% block content %}
    <div class="well col-md-6">
        {% include "tictactoe/game_list_snippet.html" with header="Games waiting for your move" games_list=waiting_games %}
        {% include "tictactoe/game_list_snippet.html" with header="Other active" games_list=other_games %}
        {% include "tictactoe/game_list_snippet.html" with header="Finished games" games_list=finished_games %}
    </div>
{% endblock content %}

tictactoe/templates/tictactoe/game_list_snippet.html
<h3 class="panel-header">{{ header }}</h3>
<div class="list-group">
    {% for game in games_list %}
        <a class="list-group-item" href="#">
            {{game}}:
            {% if game.status == "A" %}
                {% if game.next_to_move == user %}Your turn{% else %}Waiting for {% endif %}
            {% elif game.status == "D" %}
                Draw
            {% elif game.status == "F" and user == game.first_player %}
                You won!
            {% elif game.status == "S" and user == game.second_player %}
                You won!
            {% else %}
                You lost!
            {% endif %}
            <span class="badge">{{game.move_set.count}}</span>
        </a>
    {% empty %}
        <span class="list-group-item">No games available.</span>
    {% endfor %}
</div>

tictactoe/templates/tictactoe/new_invitation.html
{% extends "base.html" %}

{% block title %}
New Invitation
{% endblock title %}

{% block content %}
    <div class="well col-md-6">
        <p>Please select the user you want to invite to play a game</p>
        <form action="" method="post">
            {% csrf_token %}
            {{form}}
            <button type="submit">Send the invitation</button>
        </form>
    </div>
{% endblock content %}